# Database connection settings
PG_HOST=${DB_HOST:localhost}
PG_PORT=${DB_PORT:5432}
PG_USER=${DB_USER:massbank_user}
PG_PASSWORD=${DB_PASSWORD:massbank-password}
PG_DATABASE=${DB_NAME:records}

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://${PG_HOST}:${PG_PORT}/${PG_DATABASE}?reWriteBatchedInserts=true
spring.datasource.username=${PG_USER}
spring.datasource.password=${PG_PASSWORD}
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.properties.hibernate.jdbc.batch_size=2000
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true
spring.jpa.properties.hibernate.batch_versioned_data=true

massbank.persistence.chunk-size=2000
